### ISSUE TITLE
section headings causing errors in article conversion

### ISSUE THREAD

**Issue by tcatapano** [plazi/ggxml2taxpub#54]
In JATS the `<sec>` element must start with a `<label>` or a `<title>` element. The markup for headings in the ggxml is sometimes complex, so its likely to cause errors on output, especially if there is no heading at all under a paragraph.

**Comment by myrmoteras** [comment]
There are in fact many `<Sec>` in out treatments because they vary depending on the semantics of each paragraph.
However, each of the `<sec>` has a `<type>` attribute that could be use to create such a `<label>`?

**Comment by tcatapano** [comment]
This has been fixed in https://github.com/plazi/ggxml2taxpub/commit/fa60f64f9f2143f41b250967d57ea645a1ca7ac2  Closing.
